---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "wow-cms-data-{{ .Values.env }}-pv"
spec:
  capacity:
    storage: 10Gi  # Ajuste la taille si nécessaire
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.cms.persistence.storageClass }}  # Ici, on définit la StorageClass
  hostPath:
    path: "/srv/data/wow-cms-data-{{ .Values.env }}-pv"  # Le point de montage sur ton nœud pour les fichiers client

