apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
  namespace: {{ .Values.namespace }}
data:
  GIT_BRANCH: "{{ .Values.cms.git.branch }}"
  GIT_REPO: "{{ .Values.cms.git.repo }}"