---
apiVersion: v1
kind: Service
metadata:
  name: ac-auth
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: auth-port  # Nom du port pour la connexion WorldServer
      port: 3724
      targetPort: 3724
  selector:
    app: ac-auth
      #clusterIP: None
  type: NodePort
