apiVersion: v2
name: azerothcore
version: 1.0.0
dependencies:
  - name: ac-db
    version: 1.0.0
    repository: "file://charts/ac-db"
  - name: ac-client-data-init
    version: 1.0.0
    repository: "file://charts/ac-client-data-init"
    version: 1.0.0
    repository: "file://charts/ac-auth"
  - name: ac-worldserver
    version: 1.0.0
    repository: "file://charts/ac-worldserver"

