namespace: wow-dev

replicaCount: 1

pvc:
  pvc_name: wow-client-data-pvc
image:
  repository: landry41/ac-wotlk-client-data # ou mariadb si tu utilises cela
  tag: "master"
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClass: wow-client-storage
  size: 10Gi
