apiVersion: batch/v1
kind: Job
metadata:
  name: ac-client-data-init
spec:
  backoffLimit: 4  # Nombre maximal de tentatives avant que Kubernetes n'abandonne
  template:
    metadata:
      name: ac-client-data-init
    spec:
      containers:
        - name: ac-client-data-init
          image: landry41/ac-wotlk-client-data:master # Assure-toi d'utiliser la bonne image Docker
          volumeMounts:
            - mountPath: /azerothcore/env/dist/data
              name: client-data
      restartPolicy: OnFailure # Nous ne voulons pas redémarrer le job si tout se passe bien
      volumes:  # ❗️ La section volumes doit être DANS spec.template.spec
        - name: client-data
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.pvc_name }}  # PVC du client, à adapter si nécessaire

