---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: cms-port  # Nom du port pour la connexion WorldServer
      port: {{ .Values.cms.service.port }}
      targetPort: {{ .Values.cms.service.targetPort }}
      nodePort: {{ .Values.cms.service.nodePort }}
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
