apiVersion: batch/v1
kind: CronJob
metadata:
  name: ac-db-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 3 * * *"  # Exécution tous les jours à 3h du matin
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: mysql:8.4  # Assurez-vous d'utiliser la bonne version
              env:
                - name: MYSQL_ROOT_PASSWORD
                  value: {{ .Values.ac-db.mysqlRootPassword }}
              command:
                - "/bin/sh"
                - "-c"
                - |
                  mysqldump -h ac-db -u root -p$MYSQL_ROOT_PASSWORD --all-databases > /backup/db-$(date +\%F).sql
          restartPolicy: OnFailure