apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ac_db.service.name }}
  labels:
    app: {{ .Values.ac_db.name }}
spec:
  clusterIP: None  # Headless service
  ports:
    - port: {{ .Values.ac_db.service.port }}  # Port de la base de données
      targetPort: {{ .Values.ac_db.service.targetPort }}
  selector:
    app: {{ .Values.ac_db.name }}

