apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.ac-db.name }}
  namespace: {{ .Values.namespace }}  # Utilisation du namespace spécifié dans values.yaml
spec:
  serviceName: {{ .Values.ac-db.service.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.ac-db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ac-db.name }}
    spec:
      containers:
        - name: {{ .Values.ac-db.name }}
          image: {{ .Values.ac-db.image.repository }}:{{ .Values.ac-db.image.tag }}
          ports:
            - containerPort: {{ .Values.ac-db.service.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.ac-db.mysqlRootPassword }}
          volumeMounts:
            - name: {{ .Values.ac-db.name }}-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.ac-db.name }}-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}

